StoreApp/StoreApp.Web/Models/CategoryViewModel.cs
namespace StoreApp.Web.Models;

public class CategoryViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Url { get; set; } = string.Empty; 
}

StoreApp/StoreApp.Web/Models/MapperProfile.cs
using AutoMapper;
using StoreApp.Data.Concrete;

namespace StoreApp.Web.Models;

public class MapperProfile:Profile
{
    public MapperProfile()
    {
        CreateMap<Product, ProductViewModel>();
    }
}

StoreApp/StoreApp.Web/Models/ProductViewModel.cs
namespace StoreApp.Web.Models;

public class ProductViewModel
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public decimal Price { get; set; }

    // public string Category { get; set; } = string.Empty; //burayı siliyoruz.  
}
public class ProductListViewModel
{
    public IEnumerable<ProductViewModel> Products { get; set; } = Enumerable.Empty<ProductViewModel>();
    public PageInfo PageInfo { get; set; } = new();
    
}

public class PageInfo
{
    public int TotalItems { get; set; }
    public int ItemsPerPage { get; set; }
    public int CurrentPage { get; set; }
    public int TotalPages => (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
}

StoreApp/StoreApp.Web/Components/CategoriesListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StoreApp.Data.Abstract;
using StoreApp.Web.Models;

namespace StoreApp.Web.Components;

public class CategoriesListViewComponent:ViewComponent
{
    private readonly IStoreRepository _storeRepository;
    public CategoriesListViewComponent(IStoreRepository storeRepository)
    {
        _storeRepository = storeRepository;
    }
    public IViewComponentResult Invoke()
    {
        ViewBag.SelectedCategory = RouteData?.Values["category"];
        return View(_storeRepository.Categories.Select(c => new CategoryViewModel {
            Id = c.Id,
            Name = c.Name,
            Url = c.Url
        }).ToList());
    }
}

StoreApp/StoreApp.Web/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreApp.Data.Abstract;
using StoreApp.Web.Models;

namespace StoreApp.Web.Controllers;
public class HomeController :Controller
{
    public int pageSize = 3;
    private readonly IStoreRepository _storeRepository;
    private readonly IMapper _mapper;
    public HomeController(IStoreRepository storeRepository, IMapper mapper)
    {
        _storeRepository = storeRepository;
        _mapper = mapper;
    }
    public IActionResult Index(string category, int page = 1) 
    {
        return View(new ProductListViewModel {
            Products = _storeRepository.GetProductsByCategory(category, page, pageSize)
                .Select(product => _mapper.Map<ProductViewModel>(product)),
            PageInfo = new PageInfo {
                ItemsPerPage = pageSize,
                CurrentPage = page,
                TotalItems = _storeRepository.GetProductCount(category)
            }
        });

    }
}

StoreApp/StoreApp.Web/Views/Home/Index.cshtml
@model ProductListViewModel

<div class="row">
    <div class="col-md-3">
        <vc:categories-list />
    </div>
    <div class="col-md-9">
        @if(Model.Products.Count() == 0)
        {
            <p>Ürün bulunamadı.</p>
        }

        @foreach(var p in Model.Products)
        {
            <div class="card card-outline-secondary mb-2 p-2">
                <div class="d-flex justify-content-between">
                    <div>
                        <h4>@p.Name</h4>
                        <p>@p.Description</p>
                    </div>
                    <div>
                        <span class="badge rounded-pill text-bg-success">@p.Price TL</span>
                    </div>
                </div>
            </div>
        }

        @if(Model.PageInfo.TotalPages > 1)
        {
            <div 
                page-model="@Model.PageInfo" 
                page-action="Index"
                page-class="btn"
                page-class-link="btn-outline-secondary"
                page-class-active="btn-secondary"
                class="btn-group my-2"></div>
        }
    </div>
</div>

StoreApp/StoreApp.Web/Views/Shared/Components/CategoriesList/Default.cshtml
@model IEnumerable<CategoryViewModel>

<div class="d-grid gap-2">
    <a class="btn @(ViewBag.SelectedCategory == null ? "btn-secondary": "btn-outline-secondary")" 
        href="/products">Anasayfa</a>

    @foreach(var category in Model)
    {
        <a 
        class="btn @(ViewBag.SelectedCategory == category.Url ? "btn-secondary": "btn-outline-secondary")" 
        asp-controller="Home" asp-action="Index" asp-route-category="@category.Url">
            @category.Name
        </a>
    }
</div>

StoreApp/StoreApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body>
    <div class="bg-secondary text-white p-3">
        <div class="container">
            <span class="navbar-brand">Store App</span>
        </div>
    </div> 
    <div class="container my-3">
        @RenderBody()
    </div>

    <script src="/lib/bootstrap/jquery/jquery.min.js"></script>
    <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>